import type { Clinic, VaccineStock, RoadCondition } from './types';

export const INITIAL_VACCINE_STOCKS: VaccineStock[] = [
  { vaccine: 'COVID-19', quantity: 15000 },
  { vaccine: 'Flu', quantity: 12000 },
];

// Central Depot Location: Nairobi, Kenya
export const DEPOT_LOCATION = {
  name: 'Kenya Medical Supplies Authority (KEMSA) - Nairobi',
  coords: { lat: -1.2921, lng: 36.8219 }
};

export const MOCK_CLINICS: Clinic[] = [
  {
    id: 'C001',
    name: 'Kenyatta National Hospital',
    address: 'Hospital Rd, Upper Hill, Nairobi',
    coords: { x: 50, y: 48 },
    currentStock: { covid19: 500, flu: 600 },
    weeklyDemand: { covid19: 800, flu: 700 },
  },
  {
    id: 'C002',
    name: 'Kiambu County Referral Hospital',
    address: 'Kiambu Town, Kiambu County',
    coords: { x: 48, y: 35 },
    currentStock: { covid19: 150, flu: 200 },
    weeklyDemand: { covid19: 400, flu: 300 },
  },
  {
    id: 'C003',
    name: 'Machakos Level 5 Hospital',
    address: 'Machakos Town, Machakos County',
    coords: { x: 65, y: 55 },
    currentStock: { covid19: 80, flu: 100 },
    weeklyDemand: { covid19: 350, flu: 250 },
  },
  {
    id: 'C004',
    name: 'Thika Level 5 Hospital',
    address: 'Thika Town, Kiambu County',
    coords: { x: 55, y: 30 },
    currentStock: { covid19: 120, flu: 90 },
    weeklyDemand: { covid19: 300, flu: 200 },
  },
  {
    id: 'C005',
    name: 'Kajiado County Referral Hospital',
    address: 'Kajiado Town, Kajiado County',
    coords: { x: 40, y: 70 },
    currentStock: { covid19: 90, flu: 70 },
    weeklyDemand: { covid19: 380, flu: 280 },
  },
  {
    id: 'C006',
    name: 'Mbagathi District Hospital',
    address: 'Mbagathi Way, Nairobi',
    coords: { x: 48, y: 52 },
    currentStock: { covid19: 300, flu: 350 },
    weeklyDemand: { covid19: 600, flu: 520 },
  },
  {
    id: 'C007',
    name: 'Ruiru Sub-County Hospital',
    address: 'Ruiru Town, Kiambu County',
    coords: { x: 58, y: 40 },
    currentStock: { covid19: 100, flu: 130 },
    weeklyDemand: { covid19: 360, flu: 290 },
  },
  {
    id: 'C008',
    name: 'Kangundo Level 4 Hospital',
    address: 'Kangundo, Machakos County',
    coords: { x: 70, y: 60 },
    currentStock: { covid19: 60, flu: 50 },
    weeklyDemand: { covid19: 320, flu: 240 },
  },
  {
    id: 'C009',
    name: 'Mama Lucy Kibaki Hospital',
    address: 'Embakasi, Nairobi',
    coords: { x: 55, y: 50 },
    currentStock: { covid19: 250, flu: 300 },
    weeklyDemand: { covid19: 500, flu: 450 },
  },
  {
    id: 'C010',
    name: 'Limuru Sub-County Hospital',
    address: 'Limuru Town, Kiambu County',
    coords: { x: 40, y: 38 },
    currentStock: { covid19: 85, flu: 75 },
    weeklyDemand: { covid19: 370, flu: 300 },
  },
  {
    id: 'C011',
    name: 'Makueni County Referral Hospital',
    address: 'Wote Town, Makueni County',
    coords: { x: 60, y: 75 },
    currentStock: { covid19: 70, flu: 80 },
    weeklyDemand: { covid19: 340, flu: 270 },
  },
  {
    id: 'C012',
    name: 'Kitengela Medical Centre',
    address: 'Kitengela Town, Kajiado County',
    coords: { x: 45, y: 58 },
    currentStock: { covid19: 110, flu: 95 },
    weeklyDemand: { covid19: 330, flu: 260 },
  },
  {
    id: 'C013',
    name: 'Ngong Sub-County Hospital',
    address: 'Ngong Town, Kajiado County',
    coords: { x: 42, y: 52 },
    currentStock: { covid19: 130, flu: 110 },
    weeklyDemand: { covid19: 390, flu: 310 },
  },
  {
    id: 'C014',
    name: 'Gatundu Level 4 Hospital',
    address: 'Gatundu, Kiambu County',
    coords: { x: 52, y: 25 },
    currentStock: { covid19: 180, flu: 220 },
    weeklyDemand: { covid19: 420, flu: 350 },
  },
  {
    id: 'C015',
    name: 'Athi River Sub-County Hospital',
    address: 'Athi River, Machakos County',
    coords: { x: 58, y: 60 },
    currentStock: { covid19: 160, flu: 140 },
    weeklyDemand: { covid19: 400, flu: 330 },
  },
  {
    id: 'C016',
    name: 'Kikuyu Mission Hospital',
    address: 'Kikuyu, Kiambu County',
    coords: { x: 45, y: 45 },
    currentStock: { covid19: 200, flu: 180 },
    weeklyDemand: { covid19: 450, flu: 380 },
  },
  {
    id: 'C017',
    name: 'Mathari National Hospital',
    address: 'Mathare, Nairobi',
    coords: { x: 52, y: 46 },
    currentStock: { covid19: 350, flu: 380 },
    weeklyDemand: { covid19: 700, flu: 600 },
  },
  {
    id: 'C018',
    name: 'Karuri Health Centre',
    address: 'Karuri, Kiambu County',
    coords: { x: 46, y: 42 },
    currentStock: { covid19: 50, flu: 60 },
    weeklyDemand: { covid19: 310, flu: 250 },
  },
  {
    id: 'C019',
    name: 'Sultan Hamud Sub-County Hospital',
    address: 'Sultan Hamud, Makueni County',
    coords: { x: 55, y: 80 },
    currentStock: { covid19: 40, flu: 45 },
    weeklyDemand: { covid19: 290, flu: 230 },
  },
  {
    id: 'C020',
    name: 'Kibwezi Sub-County Hospital',
    address: 'Kibwezi, Makueni County',
    coords: { x: 68, y: 85 },
    currentStock: { covid19: 35, flu: 50 },
    weeklyDemand: { covid19: 280, flu: 220 },
  }
];

export const MOCK_ROAD_CONDITIONS: RoadCondition[] = [
  { road: 'Thika Superhighway (A2)', status: 'Clear', delayMinutes: 0 },
  { road: 'Mombasa Road (A109)', status: 'Heavy Traffic', delayMinutes: 25 },
  { road: 'Nairobi-Nakuru Highway (A104)', status: 'Clear', delayMinutes: 0 },
  { road: 'Waiyaki Way', status: 'Heavy Traffic', delayMinutes: 20 },
  { road: 'Ngong Road', status: 'Heavy Traffic', delayMinutes: 15 },
  { road: 'Kiambu Road', status: 'Clear', delayMinutes: 0 },
  { road: 'Southern Bypass', status: 'Clear', delayMinutes: 0 },
  { road: 'Eastern Bypass', status: 'Heavy Traffic', delayMinutes: 30 },
  { road: 'Machakos-Kitui Road', status: 'Clear', delayMinutes: 0 },
  { road: 'Nairobi-Namanga Road (A104)', status: 'Clear', delayMinutes: 0 },
  { road: 'Jogoo Road', status: 'Heavy Traffic', delayMinutes: 18 },
  { road: 'Kangundo Road', status: 'Clear', delayMinutes: 0 },
];